# Generated by Django 3.0.2 on 2020-02-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200214_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/blog/'),
        ),
    ]
