# Generated by Django 3.0.2 on 2020-07-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200217_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_reverse', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reverse', to='blog.Post'),
        ),
    ]
