# Generated by Django 3.0.2 on 2020-07-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200709_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='next',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_reverse', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reverse', to='blog.Post'),
        ),
    ]
